import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

export type Lang = "en" | "ka" | "ar";

interface LanguageContextType {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const saved = localStorage.getItem("hhg-lang");
    return (saved as Lang) || "en";
  });

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem("hhg-lang", l);
  };

  const dir = lang === "ar" ? "rtl" : "ltr";

  useEffect(() => {
    document.documentElement.setAttribute("dir", dir);
    document.documentElement.setAttribute("lang", lang);
  }, [lang, dir]);

  const t = (key: string): string => {
    const keys = key.split(".");
    let val: any = translations[lang];
    for (const k of keys) {
      val = val?.[k];
    }
    return (val as string) ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

/* ─── TRANSLATIONS ─── */
const translations: Record<Lang, any> = {
  en: {
    nav: {
      about: "About",
      sectors: "Sectors",
      platforms: "Platforms",
      presence: "Presence",
      esg: "ESG",
      news: "News",
      contact: "Contact",
      getInTouch: "Get in Touch",
    },
    hero: {
      tag: "Hebashi Holding Group",
      h1_1: "Building Scalable",
      h1_2: "Business Platforms",
      h1_3: "Across Emerging Markets",
      subtitle:
        "A platform builder that transforms fragmented opportunities into scalable, asset-backed ecosystems—enhanced by intelligence, integration, and strategic execution.",
      cta1: "Explore Our Platforms",
      cta2: "Who We Are",
    },
    about: {
      tag: "Who We Are",
      h2_1: "A Platform Built for",
      h2_2: "Long-Term Value",
      p1: "Hebashi Holding Group (HHG) is a diversified international holding platform that builds, scales, and operates integrated business ecosystems across high-growth sectors.",
      p2: "Established in 2008, HHG has evolved into a multi-sector investment platform operating across 7 countries, employing over 970 professionals, and maintaining exposure to 8 core industries.",
      p3: "The Group operates through a centralized holding structure, enabling disciplined capital allocation, strategic oversight, and scalable value creation across its subsidiaries and platforms.",
      est: "Est. 2008",
      estSub: "Years of Excellence",
      countries: "Countries",
      sectors: "Sectors",
      professionals: "Professionals",
    },
    model: {
      tag: "Operating Model",
      h2_1: "How We",
      h2_2: "Create Value",
      s1Title: "Platform Creation",
      s1Desc: "Strategic investments in real assets and high-potential sectors. Structuring and development of scalable opportunities.",
      s2Title: "Platform Activation",
      s2Desc: "Monetization through operations, services, and asset utilization. Diversified revenue generation models.",
      s3Title: "Platform Enablement",
      s3Desc: "Supporting infrastructure including telecommunications, education, and AI-driven systems. Capability development to sustain performance.",
      quote: '"A lifecycle-driven model designed for scalability, resilience, and performance."',
    },
    sectors: {
      tag: "Diversification",
      h2_1: "Sector",
      h2_2: "Exposure",
      desc: "Diversified across high-growth industries to support integration, resilience, and cross-sector leverage.",
      s1: "Investment & Asset Management",
      s2: "Real Estate Development",
      s3: "Construction & Engineering",
      s4: "Hospitality & Tourism",
      s5: "Telecommunications",
      s6: "Media & Production",
      s7: "Education & Learning & Development",
      s8: "Sports Investment",
    },
    platforms: {
      tag: "Integrated Ecosystem",
      h2_1: "Our",
      h2_2: "Platforms",
      desc: "HHG manages a portfolio of specialized subsidiaries and platforms, structured to ensure operational autonomy, maintain centralized strategic control, and enable data-driven capital allocation.",
      learnMore: "Learn More",
      comingSoon: "Platform page coming soon",
      virtu: {
        cat: "Investment & Real Estate",
        desc: "A modern investment company focused on creating accessible opportunities in real estate and strategic assets. Through innovation, structured investment models, and growth-driven projects, Virtu connects investors with high-potential opportunities designed for long-term value creation.",
      },
      hmpc: {
        cat: "Media & Production",
        desc: "A dynamic media and production company specializing in film production, creative content, and entertainment projects. HMPC focuses on delivering high-quality cinematic experiences, innovative storytelling, and professional production services for regional and international markets.",
      },
      batumi: {
        cat: "Hospitality & Real Estate",
        desc: "A premier real estate development and hospitality platform in Georgia. Batumi Pearl specializes in luxury property development, resort management, and strategic asset creation, positioning itself as a cornerstone of Georgia's tourism and investment landscape.",
      },
      zmc: {
        cat: "Construction & Engineering",
        desc: "Construction and engineering execution platform delivering infrastructure and development projects across emerging markets.",
      },
      ctc: {
        cat: "Telecommunications",
        desc: "Telecommunications and outsourcing solutions providing connectivity and operational excellence across regional markets.",
      },
      oti: {
        cat: "Real Estate",
        desc: "Real estate development and services platform creating premium residential and commercial properties.",
      },
      caucasus: {
        cat: "Hospitality & Tourism",
        desc: "Tourism and hospitality platform delivering exceptional travel experiences and resort management services.",
      },
    },
    presence: {
      tag: "Global Footprint",
      h2_1: "Global",
      h2_2: "Footprint",
      desc: "HHG operates across 7 countries through a hub-and-network expansion model, supported by digital coordination and data-driven oversight.",
      georgia: "Georgia",
      georgiaRole: "Core Market & Strategic Hub",
      uae: "United Arab Emirates",
      uaeRole: "Regional Hub",
      egypt: "Egypt",
      egyptRole: "North Africa",
      turkey: "Turkey",
      turkeyRole: "Crossroads Market",
      oman: "Oman",
      omanRole: "Gulf Presence",
      malaysia: "Malaysia",
      malaysiaRole: "Southeast Asia",
    },
    tech: {
      tag: "Technology",
      h2_1: "Intelligence as a",
      h2_2: "Core Layer",
      desc: "HHG integrates Artificial Intelligence and advanced data systems as a horizontal capability layer across its operations.",
      t1: "Investment Intelligence",
      t1d: "Investment intelligence and risk analysis for smarter capital allocation and opportunity identification.",
      t2: "Predictive Analytics",
      t2d: "Predictive analytics for market demand, anticipating shifts and operational needs.",
      t3: "Process Automation",
      t3d: "Process automation and operational optimization to reduce friction and increase cost efficiency.",
      t4: "Performance Monitoring",
      t4d: "Real-time dashboards and KPI tracking across all business units for continuous performance optimization.",
      quote: '"AI acts as a force multiplier—enhancing decision-making, optimizing assets, and enabling scalable growth across markets."',
    },
    esg: {
      tag: "ESG & SDG Aligned",
      h2_1: "Sustainable and",
      h2_2: "Responsible Growth",
      desc: "HHG aligns its operations with global ESG frameworks, integrating sustainability, governance, and social impact into its business model. CSR is embedded as a core operational value, aligning growth with societal impact.",
      v1: "Value Creation & Economic Growth",
      v1d: "Driving scalable investments, job creation, and infrastructure development.",
      v2: "Integrity, Governance & Accountability",
      v2d: "Ensuring transparency, compliance, and ethical operations.",
      v3: "Innovation & AI Enablement",
      v3d: "Leveraging technology and intelligence for performance and growth.",
      v4: "Sustainability & Environmental Responsibility",
      v4d: "Promoting sustainable development and responsible resource use.",
      v5: "Partnership & Global Collaboration",
      v5d: "Building cross-border strategic alliances.",
      v6: "Human Capital & Inclusion",
      v6d: "Empowering talent, diversity, and equal opportunity.",
      v7: "Corporate Social Responsibility",
      v7d: "Delivering measurable social impact through education, healthcare, and community development.",
      commitTitle: "ESG Commitment",
      commitDesc: "HHG is progressing toward alignment with international standards. The Group is committed to measurable impact, transparency, and continuous improvement.",
      gri: "Global Reporting Initiative (GRI)",
      ifc: "IFC Performance Standards",
      intl: "International ESG Disclosure Frameworks",
    },
    leadership: {
      tag: "Leadership & Governance",
      name: "Hani Hebashy",
      title: "Chairman & CEO",
      subtitle: "President of the Georgian-Arab-African Business Union",
      quote: '"We are not building for the present moment. We are building platforms that anticipate the future—where capital, opportunity, and intelligence converge to shape what comes next."',
      execTeam: "Executive Leadership Team",
      advisory: "International Advisory Council",
      legal: "Legal & Financial Experts",
      philTitle_1: "Founder's",
      philTitle_2: "Philosophy",
      phil1: "Building Platforms, Not Companies",
      phil2: "Thinking in Decades, Acting with Precision",
      phil3: "Leveraging Complexity as Advantage",
      phil4: "Expanding Ahead of Market Maturity",
      phil5: "Partnership-Driven Growth",
      phil6: "People as the Core Multiplier",
    },
    news: {
      tag: "Latest Updates",
      h2_1: "News &",
      h2_2: "Insights",
      desc: "Stay informed with the latest developments, strategic milestones, and industry insights from across the HHG ecosystem.",
      featured: "Featured",
      readFull: "Read Full Article",
      readMore: "Read More",
      comingSoon: "Full article coming soon",
      n1date: "April 15, 2026",
      n1cat: "Expansion",
      n1title: "HHG Expands Operations into Southeast Asian Markets",
      n1desc: "Hebashi Holding Group announces strategic expansion into Malaysia, strengthening its presence across emerging markets with new investment and hospitality ventures.",
      n2date: "March 28, 2026",
      n2cat: "Real Estate",
      n2title: "Batumi Pearl Launches Luxury Waterfront Development",
      n2desc: "A new premium residential and hospitality project on Georgia's Black Sea coast, setting new standards in luxury living.",
      n3date: "March 10, 2026",
      n3cat: "Technology",
      n3title: "AI-Powered Analytics Platform Deployed Across All Business Units",
      n3desc: "HHG integrates advanced artificial intelligence systems to enhance decision-making and operational performance across its portfolio.",
      n4date: "February 20, 2026",
      n4cat: "Media",
      n4title: "HMPC Secures International Film Production Partnership",
      n4desc: "A landmark collaboration bringing world-class cinematic production capabilities to regional and international markets.",
    },
    contact: {
      tag: "Contact",
      h2_1: "Get in",
      h2_2: "Touch",
      desc: "For general inquiries, partnerships, or institutional engagement, please contact us.",
      name: "Name",
      namePh: "Your full name",
      email: "Email",
      emailPh: "your@email.com",
      message: "Message",
      messagePh: "Your message...",
      submit: "Submit",
      success: "Thank you! Your message has been sent successfully.",
      successDesc: "We'll get back to you shortly.",
      hq: "Headquarters",
      hqVal: "Georgia — Core Market & Strategic Hub",
      ops: "Operations",
      opsVal: "UAE · Egypt · Turkey · Oman · Malaysia",
    },
    footer: {
      desc: "A globally recognized platform that develops sustainable, high-value ecosystems powered by innovation and intelligent systems.",
      est: "Est. 2008",
      navTitle: "Navigation",
      rights: "Hebashi Holding Group. All rights reserved.",
    },
  },

  ka: {
    nav: {
      about: "ჩვენ შესახებ",
      sectors: "სექტორები",
      platforms: "პლატფორმები",
      presence: "გეოგრაფია",
      esg: "ESG",
      news: "სიახლეები",
      contact: "კონტაქტი",
      getInTouch: "დაგვიკავშირდით",
    },
    hero: {
      tag: "ჰებაში ჰოლდინგ ჯგუფი",
      h1_1: "მასშტაბირებადი",
      h1_2: "ბიზნეს პლატფორმების",
      h1_3: "შექმნა განვითარებად ბაზრებზე",
      subtitle:
        "პლატფორმების შემქმნელი, რომელიც ფრაგმენტულ შესაძლებლობებს გარდაქმნის მასშტაბირებად, აქტივებზე დაფუძნებულ ეკოსისტემებად — გაძლიერებული ინტელექტით, ინტეგრაციითა და სტრატეგიული შესრულებით.",
      cta1: "პლატფორმების ნახვა",
      cta2: "ჩვენ შესახებ",
    },
    about: {
      tag: "ჩვენ შესახებ",
      h2_1: "პლატფორმა შექმნილი",
      h2_2: "გრძელვადიანი ღირებულებისთვის",
      p1: "ჰებაში ჰოლდინგ ჯგუფი (HHG) არის დივერსიფიცირებული საერთაშორისო ჰოლდინგ პლატფორმა, რომელიც აშენებს, ზრდის და მართავს ინტეგრირებულ ბიზნეს ეკოსისტემებს მაღალი ზრდის სექტორებში.",
      p2: "2008 წელს დაარსებული, HHG გადაიქცა მულტისექტორულ საინვესტიციო პლატფორმად, რომელიც მოქმედებს 7 ქვეყანაში, ასაქმებს 970-ზე მეტ პროფესიონალს და მოიცავს 8 ძირითად ინდუსტრიას.",
      p3: "ჯგუფი მოქმედებს ცენტრალიზებული ჰოლდინგ სტრუქტურით, რაც უზრუნველყოფს დისციპლინირებულ კაპიტალის განაწილებას, სტრატეგიულ ზედამხედველობას და მასშტაბირებად ღირებულების შექმნას.",
      est: "დაარსდა 2008",
      estSub: "წლების გამოცდილება",
      countries: "ქვეყანა",
      sectors: "სექტორი",
      professionals: "პროფესიონალი",
    },
    model: {
      tag: "ოპერაციული მოდელი",
      h2_1: "როგორ ვქმნით",
      h2_2: "ღირებულებას",
      s1Title: "პლატფორმის შექმნა",
      s1Desc: "სტრატეგიული ინვესტიციები რეალურ აქტივებსა და მაღალი პოტენციალის სექტორებში. მასშტაბირებადი შესაძლებლობების სტრუქტურირება და განვითარება.",
      s2Title: "პლატფორმის გააქტიურება",
      s2Desc: "მონეტიზაცია ოპერაციების, სერვისებისა და აქტივების გამოყენებით. დივერსიფიცირებული შემოსავლის მოდელები.",
      s3Title: "პლატფორმის მხარდაჭერა",
      s3Desc: "მხარდამჭერი ინფრასტრუქტურა, მათ შორის ტელეკომუნიკაციები, განათლება და AI-ზე დაფუძნებული სისტემები.",
      quote: '"სასიცოცხლო ციკლზე დაფუძნებული მოდელი, შექმნილი მასშტაბირებადობის, მდგრადობისა და ეფექტურობისთვის."',
    },
    sectors: {
      tag: "დივერსიფიკაცია",
      h2_1: "სექტორული",
      h2_2: "ექსპოზიცია",
      desc: "დივერსიფიცირებული მაღალი ზრდის ინდუსტრიებში ინტეგრაციის, მდგრადობისა და ჯვარედინი სექტორული ბერკეტის მხარდასაჭერად.",
      s1: "ინვესტიციები და აქტივების მართვა",
      s2: "უძრავი ქონების განვითარება",
      s3: "მშენებლობა და ინჟინერია",
      s4: "სტუმართმოყვარეობა და ტურიზმი",
      s5: "ტელეკომუნიკაციები",
      s6: "მედია და პროდუქცია",
      s7: "განათლება და სწავლა და განვითარება",
      s8: "სპორტული ინვესტიციები",
    },
    platforms: {
      tag: "ინტეგრირებული ეკოსისტემა",
      h2_1: "ჩვენი",
      h2_2: "პლატფორმები",
      desc: "HHG მართავს სპეციალიზებული შვილობილი კომპანიებისა და პლატფორმების პორტფელს, სტრუქტურირებულს ოპერაციული ავტონომიის, ცენტრალიზებული სტრატეგიული კონტროლისა და მონაცემებზე დაფუძნებული კაპიტალის განაწილების უზრუნველსაყოფად.",
      learnMore: "გაიგე მეტი",
      comingSoon: "პლატფორმის გვერდი მალე",
      virtu: {
        cat: "ინვესტიციები და უძრავი ქონება",
        desc: "თანამედროვე საინვესტიციო კომპანია, ორიენტირებული უძრავ ქონებასა და სტრატეგიულ აქტივებში ხელმისაწვდომი შესაძლებლობების შექმნაზე.",
      },
      hmpc: {
        cat: "მედია და პროდუქცია",
        desc: "დინამიური მედია და საპროდუქციო კომპანია, სპეციალიზირებული ფილმების წარმოებაში, შემოქმედებით კონტენტსა და გასართობ პროექტებში.",
      },
      batumi: {
        cat: "სტუმართმოყვარეობა და უძრავი ქონება",
        desc: "პრემიერ უძრავი ქონების განვითარებისა და სტუმართმოყვარეობის პლატფორმა საქართველოში. ბათუმი პერლი სპეციალიზდება ლუქს ქონების განვითარებაში.",
      },
      zmc: {
        cat: "მშენებლობა და ინჟინერია",
        desc: "მშენებლობისა და ინჟინერიის შესრულების პლატფორმა, რომელიც ახორციელებს ინფრასტრუქტურულ და განვითარების პროექტებს.",
      },
      ctc: {
        cat: "ტელეკომუნიკაციები",
        desc: "ტელეკომუნიკაციებისა და აუთსორსინგის გადაწყვეტილებები, რომლებიც უზრუნველყოფენ კავშირგაბმულობას და ოპერაციულ სრულყოფილებას.",
      },
      oti: {
        cat: "უძრავი ქონება",
        desc: "უძრავი ქონების განვითარებისა და მომსახურების პლატფორმა, რომელიც ქმნის პრემიუმ საცხოვრებელ და კომერციულ ობიექტებს.",
      },
      caucasus: {
        cat: "სტუმართმოყვარეობა და ტურიზმი",
        desc: "ტურიზმისა და სტუმართმოყვარეობის პლატფორმა, რომელიც უზრუნველყოფს განსაკუთრებულ სამოგზაურო გამოცდილებას.",
      },
    },
    presence: {
      tag: "გლობალური კვალი",
      h2_1: "გლობალური",
      h2_2: "კვალი",
      desc: "HHG მოქმედებს 7 ქვეყანაში ჰაბ-და-ქსელის გაფართოების მოდელით, მხარდაჭერილი ციფრული კოორდინაციითა და მონაცემებზე დაფუძნებული ზედამხედველობით.",
      georgia: "საქართველო",
      georgiaRole: "ძირითადი ბაზარი და სტრატეგიული ჰაბი",
      uae: "არაბთა გაერთიანებული საამიროები",
      uaeRole: "რეგიონული ჰაბი",
      egypt: "ეგვიპტე",
      egyptRole: "ჩრდილოეთ აფრიკა",
      turkey: "თურქეთი",
      turkeyRole: "გზაჯვარედინი ბაზარი",
      oman: "ომანი",
      omanRole: "სპარსეთის ყურის ყოფნა",
      malaysia: "მალაიზია",
      malaysiaRole: "სამხრეთ-აღმოსავლეთ აზია",
    },
    tech: {
      tag: "ტექნოლოგია",
      h2_1: "ინტელექტი როგორც",
      h2_2: "ძირითადი ფენა",
      desc: "HHG ინტეგრირებს ხელოვნურ ინტელექტს და მოწინავე მონაცემთა სისტემებს, როგორც ჰორიზონტალურ შესაძლებლობების ფენას მთელ ოპერაციებში.",
      t1: "საინვესტიციო ინტელექტი",
      t1d: "საინვესტიციო ინტელექტი და რისკის ანალიზი კაპიტალის უფრო ჭკვიანი განაწილებისთვის.",
      t2: "პროგნოზირებადი ანალიტიკა",
      t2d: "საბაზრო მოთხოვნის პროგნოზირებადი ანალიტიკა, ცვლილებებისა და ოპერაციული საჭიროებების წინასწარ განჭვრეტა.",
      t3: "პროცესის ავტომატიზაცია",
      t3d: "პროცესის ავტომატიზაცია და ოპერაციული ოპტიმიზაცია ხარჯების ეფექტურობის გასაზრდელად.",
      t4: "შესრულების მონიტორინგი",
      t4d: "რეალურ დროში დაფები და KPI თვალყურის დევნება ყველა ბიზნეს ერთეულში.",
      quote: '"AI მოქმედებს როგორც ძალის მულტიპლიკატორი — აძლიერებს გადაწყვეტილების მიღებას, ოპტიმიზაციას უკეთებს აქტივებს და უზრუნველყოფს მასშტაბირებად ზრდას."',
    },
    esg: {
      tag: "ESG & SDG შესაბამისი",
      h2_1: "მდგრადი და",
      h2_2: "პასუხისმგებლიანი ზრდა",
      desc: "HHG ასწორებს თავის ოპერაციებს გლობალურ ESG ჩარჩოებთან, ინტეგრირებს მდგრადობას, მმართველობას და სოციალურ გავლენას ბიზნეს მოდელში.",
      v1: "ღირებულების შექმნა და ეკონომიკური ზრდა",
      v1d: "მასშტაბირებადი ინვესტიციების, სამუშაო ადგილების შექმნისა და ინფრასტრუქტურის განვითარების ხელშეწყობა.",
      v2: "მთლიანობა, მმართველობა და ანგარიშვალდებულება",
      v2d: "გამჭვირვალობის, შესაბამისობისა და ეთიკური ოპერაციების უზრუნველყოფა.",
      v3: "ინოვაცია და AI გაძლიერება",
      v3d: "ტექნოლოგიისა და ინტელექტის გამოყენება შესრულებისა და ზრდისთვის.",
      v4: "მდგრადობა და გარემოსდაცვითი პასუხისმგებლობა",
      v4d: "მდგრადი განვითარებისა და რესურსების პასუხისმგებლიანი გამოყენების ხელშეწყობა.",
      v5: "პარტნიორობა და გლობალური თანამშრომლობა",
      v5d: "ტრანსსასაზღვრო სტრატეგიული ალიანსების შექმნა.",
      v6: "ადამიანური კაპიტალი და ინკლუზია",
      v6d: "ნიჭის, მრავალფეროვნებისა და თანაბარი შესაძლებლობების გაძლიერება.",
      v7: "კორპორაციული სოციალური პასუხისმგებლობა",
      v7d: "გაზომვადი სოციალური გავლენის მიწოდება განათლების, ჯანდაცვისა და საზოგადოების განვითარების გზით.",
      commitTitle: "ESG ვალდებულება",
      commitDesc: "HHG პროგრესირებს საერთაშორისო სტანდარტებთან შესაბამისობისკენ. ჯგუფი ვალდებულია გაზომვადი გავლენის, გამჭვირვალობისა და მუდმივი გაუმჯობესებისკენ.",
      gri: "გლობალური ანგარიშგების ინიციატივა (GRI)",
      ifc: "IFC შესრულების სტანდარტები",
      intl: "საერთაშორისო ESG გამჟღავნების ჩარჩოები",
    },
    leadership: {
      tag: "ხელმძღვანელობა და მმართველობა",
      name: "ჰანი ჰებაში",
      title: "თავმჯდომარე და აღმასრულებელი დირექტორი",
      subtitle: "ქართულ-არაბულ-აფრიკული ბიზნეს კავშირის პრეზიდენტი",
      quote: '"ჩვენ არ ვაშენებთ ამჟამინდელი მომენტისთვის. ჩვენ ვაშენებთ პლატფორმებს, რომლებიც წინასწარ ხედავენ მომავალს — სადაც კაპიტალი, შესაძლებლობა და ინტელექტი ერთიანდება იმის ჩამოსაყალიბებლად, რაც მოდის."',
      execTeam: "აღმასრულებელი ხელმძღვანელობის გუნდი",
      advisory: "საერთაშორისო საკონსულტაციო საბჭო",
      legal: "იურიდიული და ფინანსური ექსპერტები",
      philTitle_1: "დამფუძნებლის",
      philTitle_2: "ფილოსოფია",
      phil1: "პლატფორმების შექმნა, არა კომპანიების",
      phil2: "ათწლეულებში აზროვნება, სიზუსტით მოქმედება",
      phil3: "სირთულის, როგორც უპირატესობის გამოყენება",
      phil4: "ბაზრის სიმწიფემდე გაფართოება",
      phil5: "პარტნიორობაზე დაფუძნებული ზრდა",
      phil6: "ადამიანები, როგორც ძირითადი მულტიპლიკატორი",
    },
    news: {
      tag: "უახლესი განახლებები",
      h2_1: "სიახლეები და",
      h2_2: "ინსაითები",
      desc: "იყავით ინფორმირებული უახლესი მოვლენების, სტრატეგიული მიღწევებისა და ინდუსტრიული ინსაითების შესახებ HHG ეკოსისტემიდან.",
      featured: "გამორჩეული",
      readFull: "სრული სტატიის წაკითხვა",
      readMore: "წაიკითხე მეტი",
      comingSoon: "სრული სტატია მალე",
      n1date: "15 აპრილი, 2026",
      n1cat: "გაფართოება",
      n1title: "HHG აფართოებს ოპერაციებს სამხრეთ-აღმოსავლეთ აზიის ბაზრებზე",
      n1desc: "ჰებაში ჰოლდინგ ჯგუფი აცხადებს სტრატეგიულ გაფართოებას მალაიზიაში.",
      n2date: "28 მარტი, 2026",
      n2cat: "უძრავი ქონება",
      n2title: "ბათუმი პერლი იწყებს ლუქს სანაპირო განვითარებას",
      n2desc: "ახალი პრემიუმ საცხოვრებელი და სტუმართმოყვარეობის პროექტი საქართველოს შავი ზღვის სანაპიროზე.",
      n3date: "10 მარტი, 2026",
      n3cat: "ტექნოლოგია",
      n3title: "AI-ზე დაფუძნებული ანალიტიკის პლატფორმა განლაგებულია ყველა ბიზნეს ერთეულში",
      n3desc: "HHG ინტეგრირებს მოწინავე ხელოვნური ინტელექტის სისტემებს გადაწყვეტილების მიღების გასაუმჯობესებლად.",
      n4date: "20 თებერვალი, 2026",
      n4cat: "მედია",
      n4title: "HMPC უზრუნველყოფს საერთაშორისო ფილმის წარმოების პარტნიორობას",
      n4desc: "მნიშვნელოვანი თანამშრომლობა მსოფლიო დონის კინემატოგრაფიული წარმოების შესაძლებლობების მოტანისთვის.",
    },
    contact: {
      tag: "კონტაქტი",
      h2_1: "დაგვი-",
      h2_2: "კავშირდით",
      desc: "ზოგადი შეკითხვების, პარტნიორობის ან ინსტიტუციური ჩართულობისთვის, გთხოვთ დაგვიკავშირდეთ.",
      name: "სახელი",
      namePh: "თქვენი სრული სახელი",
      email: "ელ-ფოსტა",
      emailPh: "your@email.com",
      message: "შეტყობინება",
      messagePh: "თქვენი შეტყობინება...",
      submit: "გაგზავნა",
      success: "გმადლობთ! თქვენი შეტყობინება წარმატებით გაიგზავნა.",
      successDesc: "მალე დაგიკავშირდებით.",
      hq: "სათავო ოფისი",
      hqVal: "საქართველო — ძირითადი ბაზარი და სტრატეგიული ჰაბი",
      ops: "ოპერაციები",
      opsVal: "UAE · ეგვიპტე · თურქეთი · ომანი · მალაიზია",
    },
    footer: {
      desc: "გლობალურად აღიარებული პლატფორმა, რომელიც ავითარებს მდგრად, მაღალი ღირებულების ეკოსისტემებს ინოვაციითა და ინტელექტუალური სისტემებით.",
      est: "დაარსდა 2008",
      navTitle: "ნავიგაცია",
      rights: "ჰებაში ჰოლდინგ ჯგუფი. ყველა უფლება დაცულია.",
    },
  },

  ar: {
    nav: {
      about: "من نحن",
      sectors: "القطاعات",
      platforms: "المنصات",
      presence: "التواجد",
      esg: "الاستدامة",
      news: "الأخبار",
      contact: "اتصل بنا",
      getInTouch: "تواصل معنا",
    },
    hero: {
      tag: "مجموعة حباشي القابضة",
      h1_1: "بناء منصات",
      h1_2: "أعمال قابلة للتوسع",
      h1_3: "عبر الأسواق الناشئة",
      subtitle:
        "منشئ منصات يحوّل الفرص المجزأة إلى أنظمة بيئية قابلة للتوسع ومدعومة بالأصول — معززة بالذكاء والتكامل والتنفيذ الاستراتيجي.",
      cta1: "استكشف منصاتنا",
      cta2: "من نحن",
    },
    about: {
      tag: "من نحن",
      h2_1: "منصة مبنية من أجل",
      h2_2: "القيمة طويلة الأمد",
      p1: "مجموعة حباشي القابضة (HHG) هي منصة قابضة دولية متنوعة تبني وتوسع وتدير أنظمة بيئية تجارية متكاملة عبر قطاعات عالية النمو.",
      p2: "تأسست عام 2008، وتطورت HHG إلى منصة استثمارية متعددة القطاعات تعمل في 7 دول، وتوظف أكثر من 970 متخصصاً، وتحافظ على تعرض لـ 8 صناعات أساسية.",
      p3: "تعمل المجموعة من خلال هيكل قابض مركزي، مما يتيح تخصيص رأس المال المنضبط والرقابة الاستراتيجية وخلق القيمة القابلة للتوسع عبر شركاتها التابعة ومنصاتها.",
      est: "تأسست 2008",
      estSub: "سنوات من التميز",
      countries: "دول",
      sectors: "قطاعات",
      professionals: "متخصص",
    },
    model: {
      tag: "نموذج التشغيل",
      h2_1: "كيف نخلق",
      h2_2: "القيمة",
      s1Title: "إنشاء المنصة",
      s1Desc: "استثمارات استراتيجية في الأصول الحقيقية والقطاعات ذات الإمكانات العالية. هيكلة وتطوير الفرص القابلة للتوسع.",
      s2Title: "تفعيل المنصة",
      s2Desc: "تحقيق الدخل من خلال العمليات والخدمات واستخدام الأصول. نماذج إيرادات متنوعة.",
      s3Title: "تمكين المنصة",
      s3Desc: "بنية تحتية داعمة تشمل الاتصالات والتعليم والأنظمة المدعومة بالذكاء الاصطناعي. تطوير القدرات للحفاظ على الأداء.",
      quote: '"نموذج قائم على دورة الحياة مصمم للتوسع والمرونة والأداء."',
    },
    sectors: {
      tag: "التنويع",
      h2_1: "التعرض",
      h2_2: "القطاعي",
      desc: "متنوعة عبر صناعات عالية النمو لدعم التكامل والمرونة والرافعة عبر القطاعات.",
      s1: "الاستثمار وإدارة الأصول",
      s2: "تطوير العقارات",
      s3: "البناء والهندسة",
      s4: "الضيافة والسياحة",
      s5: "الاتصالات",
      s6: "الإعلام والإنتاج",
      s7: "التعليم والتعلم والتطوير",
      s8: "الاستثمار الرياضي",
    },
    platforms: {
      tag: "النظام البيئي المتكامل",
      h2_1: "منصاتنا",
      h2_2: "",
      desc: "تدير HHG محفظة من الشركات التابعة والمنصات المتخصصة، مهيكلة لضمان الاستقلالية التشغيلية والسيطرة الاستراتيجية المركزية وتخصيص رأس المال القائم على البيانات.",
      learnMore: "اعرف المزيد",
      comingSoon: "صفحة المنصة قريباً",
      virtu: {
        cat: "الاستثمار والعقارات",
        desc: "شركة استثمارية حديثة تركز على خلق فرص متاحة في العقارات والأصول الاستراتيجية. من خلال الابتكار ونماذج الاستثمار المهيكلة والمشاريع المدفوعة بالنمو.",
      },
      hmpc: {
        cat: "الإعلام والإنتاج",
        desc: "شركة إعلام وإنتاج ديناميكية متخصصة في إنتاج الأفلام والمحتوى الإبداعي والمشاريع الترفيهية. تركز HMPC على تقديم تجارب سينمائية عالية الجودة.",
      },
      batumi: {
        cat: "الضيافة والعقارات",
        desc: "منصة رائدة لتطوير العقارات والضيافة في جورجيا. تتخصص باتومي بيرل في تطوير العقارات الفاخرة وإدارة المنتجعات وإنشاء الأصول الاستراتيجية.",
      },
      zmc: {
        cat: "البناء والهندسة",
        desc: "منصة تنفيذ البناء والهندسة التي تقدم مشاريع البنية التحتية والتطوير عبر الأسواق الناشئة.",
      },
      ctc: {
        cat: "الاتصالات",
        desc: "حلول الاتصالات والتعهيد التي توفر الاتصال والتميز التشغيلي عبر الأسواق الإقليمية.",
      },
      oti: {
        cat: "العقارات",
        desc: "منصة تطوير وخدمات العقارات التي تنشئ عقارات سكنية وتجارية متميزة.",
      },
      caucasus: {
        cat: "الضيافة والسياحة",
        desc: "منصة السياحة والضيافة التي تقدم تجارب سفر استثنائية وخدمات إدارة المنتجعات.",
      },
    },
    presence: {
      tag: "البصمة العالمية",
      h2_1: "البصمة",
      h2_2: "العالمية",
      desc: "تعمل HHG في 7 دول من خلال نموذج توسع المحور والشبكة، مدعوماً بالتنسيق الرقمي والرقابة القائمة على البيانات.",
      georgia: "جورجيا",
      georgiaRole: "السوق الأساسي والمحور الاستراتيجي",
      uae: "الإمارات العربية المتحدة",
      uaeRole: "المحور الإقليمي",
      egypt: "مصر",
      egyptRole: "شمال أفريقيا",
      turkey: "تركيا",
      turkeyRole: "سوق مفترق الطرق",
      oman: "عُمان",
      omanRole: "التواجد في الخليج",
      malaysia: "ماليزيا",
      malaysiaRole: "جنوب شرق آسيا",
    },
    tech: {
      tag: "التكنولوجيا",
      h2_1: "الذكاء كطبقة",
      h2_2: "أساسية",
      desc: "تدمج HHG الذكاء الاصطناعي وأنظمة البيانات المتقدمة كطبقة قدرات أفقية عبر عملياتها.",
      t1: "الذكاء الاستثماري",
      t1d: "الذكاء الاستثماري وتحليل المخاطر لتخصيص رأس المال الأذكى وتحديد الفرص.",
      t2: "التحليلات التنبؤية",
      t2d: "التحليلات التنبؤية للطلب في السوق، وتوقع التحولات والاحتياجات التشغيلية.",
      t3: "أتمتة العمليات",
      t3d: "أتمتة العمليات والتحسين التشغيلي لتقليل الاحتكاك وزيادة كفاءة التكلفة.",
      t4: "مراقبة الأداء",
      t4d: "لوحات معلومات في الوقت الفعلي وتتبع مؤشرات الأداء الرئيسية عبر جميع وحدات الأعمال.",
      quote: '"يعمل الذكاء الاصطناعي كمضاعف للقوة — يعزز اتخاذ القرار ويحسن الأصول ويمكّن النمو القابل للتوسع عبر الأسواق."',
    },
    esg: {
      tag: "متوافق مع ESG و SDG",
      h2_1: "نمو مستدام",
      h2_2: "ومسؤول",
      desc: "تواءم HHG عملياتها مع أطر ESG العالمية، وتدمج الاستدامة والحوكمة والأثر الاجتماعي في نموذج أعمالها. المسؤولية الاجتماعية مدمجة كقيمة تشغيلية أساسية.",
      v1: "خلق القيمة والنمو الاقتصادي",
      v1d: "دفع الاستثمارات القابلة للتوسع وخلق فرص العمل وتطوير البنية التحتية.",
      v2: "النزاهة والحوكمة والمساءلة",
      v2d: "ضمان الشفافية والامتثال والعمليات الأخلاقية.",
      v3: "الابتكار وتمكين الذكاء الاصطناعي",
      v3d: "الاستفادة من التكنولوجيا والذكاء للأداء والنمو.",
      v4: "الاستدامة والمسؤولية البيئية",
      v4d: "تعزيز التنمية المستدامة والاستخدام المسؤول للموارد.",
      v5: "الشراكة والتعاون العالمي",
      v5d: "بناء تحالفات استراتيجية عابرة للحدود.",
      v6: "رأس المال البشري والشمول",
      v6d: "تمكين المواهب والتنوع وتكافؤ الفرص.",
      v7: "المسؤولية الاجتماعية للشركات",
      v7d: "تقديم أثر اجتماعي قابل للقياس من خلال التعليم والرعاية الصحية وتنمية المجتمع.",
      commitTitle: "التزام ESG",
      commitDesc: "تتقدم HHG نحو التوافق مع المعايير الدولية. المجموعة ملتزمة بالأثر القابل للقياس والشفافية والتحسين المستمر.",
      gri: "مبادرة التقارير العالمية (GRI)",
      ifc: "معايير أداء IFC",
      intl: "أطر الإفصاح الدولية لـ ESG",
    },
    leadership: {
      tag: "القيادة والحوكمة",
      name: "هاني حباشي",
      title: "رئيس مجلس الإدارة والرئيس التنفيذي",
      subtitle: "رئيس اتحاد الأعمال الجورجي العربي الأفريقي",
      quote: '"نحن لا نبني للحظة الحالية. نحن نبني منصات تستشرف المستقبل — حيث يتقاطع رأس المال والفرصة والذكاء لتشكيل ما هو قادم."',
      execTeam: "فريق القيادة التنفيذية",
      advisory: "المجلس الاستشاري الدولي",
      legal: "خبراء قانونيون وماليون",
      philTitle_1: "فلسفة",
      philTitle_2: "المؤسس",
      phil1: "بناء منصات، وليس شركات",
      phil2: "التفكير بالعقود، والتنفيذ بدقة",
      phil3: "استثمار التعقيد كميزة",
      phil4: "التوسع قبل نضج السوق",
      phil5: "نمو مدفوع بالشراكة",
      phil6: "الناس كمضاعف أساسي",
    },
    news: {
      tag: "آخر التحديثات",
      h2_1: "الأخبار",
      h2_2: "والرؤى",
      desc: "ابقَ على اطلاع بأحدث التطورات والمعالم الاستراتيجية والرؤى الصناعية من نظام HHG البيئي.",
      featured: "مميز",
      readFull: "اقرأ المقال كاملاً",
      readMore: "اقرأ المزيد",
      comingSoon: "المقال الكامل قريباً",
      n1date: "15 أبريل 2026",
      n1cat: "التوسع",
      n1title: "HHG توسع عملياتها في أسواق جنوب شرق آسيا",
      n1desc: "تعلن مجموعة حباشي القابضة عن توسع استراتيجي في ماليزيا، معززة تواجدها عبر الأسواق الناشئة.",
      n2date: "28 مارس 2026",
      n2cat: "العقارات",
      n2title: "باتومي بيرل تطلق مشروع تطوير واجهة بحرية فاخرة",
      n2desc: "مشروع سكني وضيافة متميز جديد على ساحل البحر الأسود في جورجيا.",
      n3date: "10 مارس 2026",
      n3cat: "التكنولوجيا",
      n3title: "نشر منصة تحليلات مدعومة بالذكاء الاصطناعي عبر جميع وحدات الأعمال",
      n3desc: "تدمج HHG أنظمة ذكاء اصطناعي متقدمة لتعزيز اتخاذ القرار والأداء التشغيلي.",
      n4date: "20 فبراير 2026",
      n4cat: "الإعلام",
      n4title: "HMPC تؤمن شراكة إنتاج أفلام دولية",
      n4desc: "تعاون بارز يجلب قدرات إنتاج سينمائي عالمية المستوى للأسواق الإقليمية والدولية.",
    },
    contact: {
      tag: "اتصل بنا",
      h2_1: "تواصل",
      h2_2: "معنا",
      desc: "للاستفسارات العامة أو الشراكات أو المشاركة المؤسسية، يرجى التواصل معنا.",
      name: "الاسم",
      namePh: "اسمك الكامل",
      email: "البريد الإلكتروني",
      emailPh: "your@email.com",
      message: "الرسالة",
      messagePh: "رسالتك...",
      submit: "إرسال",
      success: "شكراً لك! تم إرسال رسالتك بنجاح.",
      successDesc: "سنتواصل معك قريباً.",
      hq: "المقر الرئيسي",
      hqVal: "جورجيا — السوق الأساسي والمحور الاستراتيجي",
      ops: "العمليات",
      opsVal: "الإمارات · مصر · تركيا · عُمان · ماليزيا",
    },
    footer: {
      desc: "منصة معترف بها عالمياً تطور أنظمة بيئية مستدامة وعالية القيمة مدعومة بالابتكار والأنظمة الذكية.",
      est: "تأسست 2008",
      navTitle: "التنقل",
      rights: "مجموعة حباشي القابضة. جميع الحقوق محفوظة.",
    },
  },
};
